package Interfaces;

import Clases.Main;
import Clases.Planta1.Botones1;
import Clases.Planta1.Camaras1;
import Clases.Planta1.Ensambladores1;
import Clases.Planta1.Pantallas1;
import Clases.Planta1.Pines1;
import Clases.Planta2.Botones2;
import Clases.Planta2.Camaras2;
import Clases.Planta2.Ensambladores2;
import Clases.Planta2.Gerente2;
import Clases.Planta2.Jefe2;
import Clases.Planta2.Pantallas2;
import Clases.Planta2.Pines2;
import java.util.concurrent.Semaphore;

public class Inicio extends javax.swing.JFrame {
    public static Planta2 planta2 = new Planta2();
    public static Planta1 planta1 = new Planta1();
    public Inicio() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parametros = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        parametros.setBackground(new java.awt.Color(255, 255, 255));
        parametros.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        parametros.setText("Modificar Parámetros");
        parametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametrosActionPerformed(evt);
            }
        });

        iniciar.setBackground(new java.awt.Color(255, 255, 255));
        iniciar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iniciar.setText("Iniciar Simulación");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel1.setText("Sony");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(iniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(parametros)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(iniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parametros)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        
        //Apertura de interfaz.
        Simulacion simulacion = new Simulacion();
        simulacion.setLocationRelativeTo(null);
        simulacion.setVisible(true);
        
        

        //Creación de Semáforos de Productores.
        Semaphore pantallas1Productor = new Semaphore(Main.pantallas1Almacen);
        Semaphore botones1Productor = new Semaphore(Main.botones1Almacen);
        Semaphore pines1Productor = new Semaphore(Main.pines1Almacen);
        Semaphore camaras1Productor = new Semaphore(Main.camaras1Almacen);
        
        Semaphore pantallas2Productor = new Semaphore(Main.pantallas2Almacen);
        Semaphore botones2Productor = new Semaphore(Main.botones2Almacen);
        Semaphore pines2Productor = new Semaphore(Main.pines2Almacen);
        Semaphore camaras2Productor = new Semaphore(Main.camaras2Almacen);
        
        Semaphore pantallas1Mutex = new Semaphore(1);
        Semaphore botones1Mutex = new Semaphore(1);
        Semaphore pines1Mutex = new Semaphore(1);
        Semaphore camaras1Mutex = new Semaphore(1);
        
        Semaphore pantallas2Mutex = new Semaphore(1);
        Semaphore botones2Mutex = new Semaphore(1);
        Semaphore pines2Mutex = new Semaphore(1);
        Semaphore camaras2Mutex = new Semaphore(1);
        
        //Creación de Semáforoes de Ensambladores
        Semaphore pantallas1Ensamblador = new Semaphore(0);
        Semaphore botones1Ensamblador = new Semaphore(0);
        Semaphore pines1Ensamblador = new Semaphore(0);
        Semaphore camaras1Ensamblador = new Semaphore(0);
        Semaphore ensamblador1Mutex = new Semaphore(1);
        
        Semaphore pantallas2Ensamblador = new Semaphore(0);
        Semaphore botones2Ensamblador = new Semaphore(0);
        Semaphore pines2Ensamblador = new Semaphore(0);
        Semaphore camaras2Ensamblador = new Semaphore(0);
        Semaphore ensamblador2Mutex = new Semaphore(1);
        
        //Inicialización de productores.
        for (int i = 0; i < Main.botones2Contratados; i++) {
            Main.listaBotones2[i] = new Botones2(botones2Productor, botones2Mutex, botones2Ensamblador);
            Main.listaBotones2[i].start();
        }
        for (int i = 0; i < Main.pantallas2Contratados; i++) {
            Main.listaPantallas2[i] = new Pantallas2(pantallas2Productor, pantallas2Mutex, pantallas2Ensamblador);
            Main.listaPantallas2[i].start();
        }
        for (int i = 0; i < Main.pines2Contratados; i++) {
            Main.listaPines2[i] = new Pines2(pines2Productor, pines2Mutex, pines2Ensamblador);
            Main.listaPines2[i].start();
        }
        for (int i = 0; i < Main.camaras2Contratados; i++) {
            Main.listaCamaras2[i] = new Camaras2(camaras2Productor, camaras2Mutex, camaras2Ensamblador);
            Main.listaCamaras2[i].start();
        }
        for (int i = 0; i < Main.ensambladores2; i++) {
            Main.listaEnsambladores2[i] = new Ensambladores2(pantallas2Ensamblador, botones2Ensamblador, pines2Ensamblador, camaras2Ensamblador, pantallas2Mutex, botones2Mutex, pines2Mutex, camaras2Mutex, pantallas2Productor, botones2Productor, pines2Productor, camaras2Productor, ensamblador2Mutex);
            Main.listaEnsambladores2[i].start();
        }
        
        //Creación de Semáforo del paso de dias.
        Semaphore diasMutex = new Semaphore(1);
        
        //Inicialización del Gerente y del Jefe.
        Jefe2 jefe2 = new Jefe2(diasMutex);
        jefe2.start();
        
        Gerente2 gerente2 = new Gerente2(diasMutex);
        gerente2.start();
        
        //Cierre de la ventana.
        this.dispose();
    }//GEN-LAST:event_iniciarActionPerformed

    private void parametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametrosActionPerformed
        Parametros parametros= new Parametros();
        parametros.setLocationRelativeTo(null);
        parametros.setVisible(true);
    }//GEN-LAST:event_parametrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton parametros;
    // End of variables declaration//GEN-END:variables
}
