package Interfaces;

import Clases.CSVEL;
import Clases.Main;
import javax.swing.JOptionPane;

public class Parametros extends javax.swing.JFrame {

    public Parametros() {
        initComponents();
        
        //Establecer en los campos los valores correspondientes.
        tiempo.setText(String.valueOf(Main.tiempo));
        tiempoRestante.setText(String.valueOf(Main.diasRestantes));
        
        pantallas1.setText(String.valueOf(Main.pantallas1Contratados));
        botones1.setText(String.valueOf(Main.botones1Contratados));
        pines1.setText(String.valueOf(Main.pines1Contratados));
        camaras1.setText(String.valueOf(Main.camaras1Contratados));
        ensambladores1.setText(String.valueOf(Main.ensambladores1));
        
        pantallas2.setText(String.valueOf(Main.pantallas2Contratados));
        botones2.setText(String.valueOf(Main.botones2Contratados));
        pines2.setText(String.valueOf(Main.pines2Contratados));
        camaras2.setText(String.valueOf(Main.camaras2Contratados));
        ensambladores2.setText(String.valueOf(Main.ensambladores2));
        
        pantallas1Almacen.setText(String.valueOf(Main.pantallas1Almacen));
        botones1Almacen.setText(String.valueOf(Main.botones1Almacen));
        pines1Almacen.setText(String.valueOf(Main.pines1Almacen));
        camaras1Almacen.setText(String.valueOf(Main.camaras1Almacen));
        
        pantallas2Almacen.setText(String.valueOf(Main.pantallas2Almacen));
        botones2Almacen.setText(String.valueOf(Main.botones2Almacen));
        pines2Almacen.setText(String.valueOf(Main.pines2Almacen));
        camaras2Almacen.setText(String.valueOf(Main.camaras2Almacen));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pantallas1 = new javax.swing.JTextField();
        botones1 = new javax.swing.JTextField();
        pines1 = new javax.swing.JTextField();
        camaras1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pantallas2 = new javax.swing.JTextField();
        botones2 = new javax.swing.JTextField();
        pines2 = new javax.swing.JTextField();
        camaras2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tiempo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pantallas1Almacen = new javax.swing.JTextField();
        botones1Almacen = new javax.swing.JTextField();
        pines1Almacen = new javax.swing.JTextField();
        camaras1Almacen = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pantallas2Almacen = new javax.swing.JTextField();
        botones2Almacen = new javax.swing.JTextField();
        pines2Almacen = new javax.swing.JTextField();
        camaras2Almacen = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tiempoRestante = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ensambladores2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ensambladores1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Productores de la planta 2 iniciales contratados:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Pantallas:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Botones:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Pines:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Camaras:");

        pantallas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pantallas1.setText("0");

        botones1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botones1.setText("0");

        pines1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pines1.setText("0");

        camaras1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        camaras1.setText("0");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Guardar Cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Pantallas:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Botones:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Pines:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Camaras:");

        pantallas2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pantallas2.setText("0");

        botones2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botones2.setText("0");

        pines2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pines2.setText("0");

        camaras2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        camaras2.setText("0");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Productores de la planta 1 iniciales contratados:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Duración días (en ms):");

        tiempo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tiempo.setText("0");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Capacidad de almacenes planta 2:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Capacidad de almacenes planta 1:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Pantallas:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Botones:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Pines:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Camaras:");

        pantallas1Almacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pantallas1Almacen.setText("0");

        botones1Almacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botones1Almacen.setText("0");

        pines1Almacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pines1Almacen.setText("0");

        camaras1Almacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        camaras1Almacen.setText("0");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Pantallas:");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Botones:");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Pines:");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Camaras:");

        pantallas2Almacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pantallas2Almacen.setText("0");

        botones2Almacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botones2Almacen.setText("0");

        pines2Almacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pines2Almacen.setText("0");

        camaras2Almacen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        camaras2Almacen.setText("0");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Días entre entregas:");

        tiempoRestante.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tiempoRestante.setText("0");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Ensambladores:");

        ensambladores2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ensambladores2.setText("0");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Ensambladores:");

        ensambladores1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ensambladores1.setText("0");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel25.setText("Parámetros iniciales de la simulación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiempoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(camaras1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(botones1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pines1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(ensambladores1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pantallas1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(camaras1Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pantallas1Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botones1Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(pines1Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel23))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(camaras2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pines2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botones2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pantallas2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ensambladores2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(camaras2Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pantallas2Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(botones2Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pines2Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pantallas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pines1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(camaras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(ensambladores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pantallas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(botones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(pines2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(camaras2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(ensambladores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pantallas1Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(botones1Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(pines1Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(camaras1Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel15)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel16)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel17))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pantallas2Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(botones2Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(pines2Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(camaras2Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel19)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel20)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel21)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel11)
                    .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tiempoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            
            //Establecer nuevo tiempo.
            int tiempo2 = Integer.parseInt(tiempo.getText());
            int diasRestantes2 = Integer.parseInt(tiempoRestante.getText());
            int entregas2 = Integer.parseInt(tiempoRestante.getText());

            //Establecer nuevos parametros de la planta 1.
            int pantallas1Contratados2 = Integer.parseInt(pantallas1.getText());
            int botones1Contratados2 = Integer.parseInt(botones1.getText());
            int pines1Contratados2 = Integer.parseInt(pines1.getText());
            int camaras1Contratados2 = Integer.parseInt(camaras1.getText());
            int ensambladores12 = Integer.parseInt(ensambladores1.getText());

            int pantallas1Almacen2 = Integer.parseInt(pantallas1Almacen.getText());
            int botones1Almacen2 = Integer.parseInt(botones1Almacen.getText());
            int pines1Almacen2 = Integer.parseInt(pines1Almacen.getText());
            int camaras1Almacen2 = Integer.parseInt(camaras1Almacen.getText());

            //Establecer nuevos parametros de la planta 2.
            int pantallas2Contratados2 = Integer.parseInt(pantallas2.getText());
            int botones2Contratados2 = Integer.parseInt(botones2.getText());
            int pines2Contratados2 = Integer.parseInt(pines2.getText());
            int camaras2Contratados2 = Integer.parseInt(camaras2.getText());
            int ensambladores22 = Integer.parseInt(ensambladores2.getText());

            int pantallas2Almacen2 = Integer.parseInt(pantallas2Almacen.getText());
            int botones2Almacen2 = Integer.parseInt(botones2Almacen.getText());
            int pines2Almacen2 = Integer.parseInt(pines2Almacen.getText());
            int camaras2Almacen2 = Integer.parseInt(camaras2Almacen.getText());
            
            
            if(tiempo2>0 && entregas2>0 && pantallas1Contratados2>0 && botones1Contratados2>0 && pines1Contratados2>0 && camaras1Contratados2>0 && ensambladores12>0 && pantallas1Almacen2>0 && botones1Almacen2>0 && pines1Almacen2>0 && camaras1Almacen2>0 && pantallas2Contratados2>0 && botones2Contratados2>0 && pines2Contratados2>0 && camaras2Contratados2>0 && ensambladores22>0 && pantallas2Almacen2>0 && botones2Almacen2>0 && pines2Almacen2>0 && camaras2Almacen2>0 && (botones2Contratados2+camaras2Contratados2+pines2Contratados2+pantallas2Contratados2 <= 15) && (botones1Contratados2+camaras1Contratados2+pines1Contratados2+pantallas1Contratados2 <= 15) ){
                //Establecer nuevo tiempo.
                Main.tiempo = Integer.parseInt(tiempo.getText());
                Main.diasRestantes = Integer.parseInt(tiempoRestante.getText());
                Main.entregas = Integer.parseInt(tiempoRestante.getText());

                //Establecer nuevos parametros de la planta 1.
                Main.pantallas1Contratados = Integer.parseInt(pantallas1.getText());
                Main.botones1Contratados = Integer.parseInt(botones1.getText());
                Main.pines1Contratados = Integer.parseInt(pines1.getText());
                Main.camaras1Contratados = Integer.parseInt(camaras1.getText());
                Main.ensambladores1 = Integer.parseInt(ensambladores1.getText());

                Main.pantallas1Almacen = Integer.parseInt(pantallas1Almacen.getText());
                Main.botones1Almacen = Integer.parseInt(botones1Almacen.getText());
                Main.pines1Almacen = Integer.parseInt(pines1Almacen.getText());
                Main.camaras1Almacen = Integer.parseInt(camaras1Almacen.getText());

                //Establecer nuevos parametros de la planta 2.
                Main.pantallas2Contratados = Integer.parseInt(pantallas2.getText());
                Main.botones2Contratados = Integer.parseInt(botones2.getText());
                Main.pines2Contratados = Integer.parseInt(pines2.getText());
                Main.camaras2Contratados = Integer.parseInt(camaras2.getText());
                Main.ensambladores2 = Integer.parseInt(ensambladores2.getText());

                Main.pantallas2Almacen = Integer.parseInt(pantallas2Almacen.getText());
                Main.botones2Almacen = Integer.parseInt(botones2Almacen.getText());
                Main.pines2Almacen = Integer.parseInt(pines2Almacen.getText());
                Main.camaras2Almacen = Integer.parseInt(camaras2Almacen.getText());

                //Establecer parámetros del histórico.
                Main.botones1Establecidos = Main.botones1Contratados;
                Main.pantallas1Establecidos = Main.pantallas1Contratados;
                Main.camaras1Establecidos = Main.camaras1Contratados;
                Main.pines1Establecidos = Main.pines1Contratados;
                Main.ensambladores1Establecidos = Main.ensambladores1;

                Main.botones2Establecidos = Main.botones2Contratados;
                Main.pantallas2Establecidos = Main.pantallas2Contratados;
                Main.camaras2Establecidos = Main.camaras2Contratados;
                Main.pines2Establecidos = Main.pines2Contratados;
                Main.ensambladores2Establecidos = Main.ensambladores2;

                if(Main.tiempo>0 && Main.entregas>0 && Main.pantallas1Contratados>0 && Main.botones1Contratados>0 && Main.pines1Contratados>0 && Main.camaras1Contratados>0 && Main.ensambladores1>0 && Main.pantallas1Almacen>0 && Main.botones1Almacen>0 && Main.pines1Almacen>0 && Main.camaras1Almacen>0 && Main.pantallas2Contratados>0 && Main.botones2Contratados>0 && Main.pines2Contratados>0 && Main.camaras2Contratados>0 && Main.ensambladores2>0 && Main.pantallas2Almacen>0 && Main.botones2Almacen>0 && Main.pines2Almacen>0 && Main.camaras2Almacen>0 && (Main.botones2Contratados+Main.camaras2Contratados+Main.pines2Contratados+Main.pantallas2Contratados <= 15) && (Main.botones1Contratados+Main.camaras1Contratados+Main.pines1Contratados+Main.pantallas1Contratados <= 15) ){
                   //Guardar cambios en el CSV.
                    CSVEL csvEscritor = new CSVEL();
                    csvEscritor.EscribirCsv(); 
                    this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Asegurate de ingresas valores mayores a 0 en los parámetros.");
            }  
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Asegurate de ingresas valores correctos en los parámetros.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField botones1;
    private static javax.swing.JTextField botones1Almacen;
    private static javax.swing.JTextField botones2;
    private static javax.swing.JTextField botones2Almacen;
    private static javax.swing.JTextField camaras1;
    private static javax.swing.JTextField camaras1Almacen;
    private static javax.swing.JTextField camaras2;
    private static javax.swing.JTextField camaras2Almacen;
    private javax.swing.JTextField ensambladores1;
    private javax.swing.JTextField ensambladores2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JTextField pantallas1;
    private static javax.swing.JTextField pantallas1Almacen;
    private static javax.swing.JTextField pantallas2;
    private static javax.swing.JTextField pantallas2Almacen;
    private static javax.swing.JTextField pines1;
    private static javax.swing.JTextField pines1Almacen;
    private static javax.swing.JTextField pines2;
    private static javax.swing.JTextField pines2Almacen;
    private javax.swing.JTextField tiempo;
    private javax.swing.JTextField tiempoRestante;
    // End of variables declaration//GEN-END:variables
}
