/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Main;

/**
 *
 * @author ijlem
 */
public class Planta2 extends javax.swing.JFrame {

    /**
     * Creates new form Planta2
     */
    public Planta2() {
        initComponents();
        botones2.setText(String.valueOf(Main.botones2Contratados));
        pantallas2.setText(String.valueOf(Main.pantallas2Contratados));
        pines2.setText(String.valueOf(Main.pines2Contratados));
        camaras2.setText(String.valueOf(Main.camaras2Contratados));
        ensambladores2.setText(String.valueOf(Main.ensambladores2));
        diasRestantes.setText(String.valueOf(Main.diasRestantes));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botones2Progreso = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        pantallas2Progreso = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        pines2Progreso = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        camaras2Progreso = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botones2 = new javax.swing.JLabel();
        pantallas2 = new javax.swing.JLabel();
        camaras2 = new javax.swing.JLabel();
        pines2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ensambladores2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        producidos2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        producidos2Total = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dias = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        diasRestantes = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jefe2 = new javax.swing.JLabel();
        gerente2 = new javax.swing.JLabel();
        botones2Gastos = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pines2Gastos = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pantallas2Gastos = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        camaras2Gastos = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ensambladores2Gastos = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ganancia = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        gananciaTotal = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jefe2Gastos = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        gerente2Gastos = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        gananciasNetas = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Ensambladores");

        botones2Progreso.setBackground(new java.awt.Color(204, 204, 204));
        botones2Progreso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botones2Progreso.setForeground(new java.awt.Color(0, 0, 0));
        botones2Progreso.setMaximum(Main.botones2Almacen);
        botones2Progreso.setString(String.valueOf(Main.botones2Producidos));
        botones2Progreso.setStringPainted(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Botones:");

        pantallas2Progreso.setBackground(new java.awt.Color(204, 204, 204));
        pantallas2Progreso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pantallas2Progreso.setForeground(new java.awt.Color(0, 0, 0));
        pantallas2Progreso.setMaximum(Main.pantallas2Almacen);
        pantallas2Progreso.setString(String.valueOf(Main.pantallas2Producidas));
        pantallas2Progreso.setStringPainted(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Pantallas:");

        pines2Progreso.setBackground(new java.awt.Color(204, 204, 204));
        pines2Progreso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pines2Progreso.setForeground(new java.awt.Color(0, 0, 0));
        pines2Progreso.setMaximum(Main.pines2Almacen);
        pines2Progreso.setString(String.valueOf(Main.pines2Producidos)
        );
        pines2Progreso.setStringPainted(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Pines:");

        camaras2Progreso.setBackground(new java.awt.Color(204, 204, 204));
        camaras2Progreso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        camaras2Progreso.setForeground(new java.awt.Color(0, 0, 0));
        camaras2Progreso.setMaximum(Main.camaras2Almacen);
        camaras2Progreso.setString(String.valueOf(Main.camaras2Producidas)
        );
        camaras2Progreso.setStringPainted(true);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Cámaras:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Almacenes");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Pantallas:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Botones:");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Pines:");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Cámaras:");

        botones2.setBackground(new java.awt.Color(255, 255, 255));
        botones2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botones2.setText("0");

        pantallas2.setBackground(new java.awt.Color(255, 255, 255));
        pantallas2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pantallas2.setText("0");

        camaras2.setBackground(new java.awt.Color(255, 255, 255));
        camaras2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        camaras2.setText("0");

        pines2.setBackground(new java.awt.Color(255, 255, 255));
        pines2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pines2.setText("0");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setText("Productores");

        ensambladores2.setBackground(new java.awt.Color(255, 255, 255));
        ensambladores2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ensambladores2.setText("0");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Ensambladores:");

        producidos2.setBackground(new java.awt.Color(255, 255, 255));
        producidos2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        producidos2.setText("0");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Ensamblados:");

        producidos2Total.setBackground(new java.awt.Color(255, 255, 255));
        producidos2Total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        producidos2Total.setText("0");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Ensamblados Total:");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setText("Jefe/Gerente");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Jefe:");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Gerente:");

        dias.setBackground(new java.awt.Color(255, 255, 255));
        dias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dias.setText("0");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Días Total:");

        diasRestantes.setBackground(new java.awt.Color(255, 255, 255));
        diasRestantes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        diasRestantes.setText("0");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Días Entrega:");

        jefe2.setBackground(new java.awt.Color(255, 255, 255));
        jefe2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jefe2.setText("Estado");

        gerente2.setBackground(new java.awt.Color(255, 255, 255));
        gerente2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gerente2.setText("Estado");

        botones2Gastos.setBackground(new java.awt.Color(255, 255, 255));
        botones2Gastos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botones2Gastos.setText("0");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Gastos:");

        pines2Gastos.setBackground(new java.awt.Color(255, 255, 255));
        pines2Gastos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pines2Gastos.setText("0");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Gastos:");

        pantallas2Gastos.setBackground(new java.awt.Color(255, 255, 255));
        pantallas2Gastos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pantallas2Gastos.setText("0");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Gastos:");

        camaras2Gastos.setBackground(new java.awt.Color(255, 255, 255));
        camaras2Gastos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        camaras2Gastos.setText("0");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Gastos:");

        ensambladores2Gastos.setBackground(new java.awt.Color(255, 255, 255));
        ensambladores2Gastos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ensambladores2Gastos.setText("0");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("Gastos:");

        ganancia.setBackground(new java.awt.Color(255, 255, 255));
        ganancia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ganancia.setText("0");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("Ganancia:");

        gananciaTotal.setBackground(new java.awt.Color(255, 255, 255));
        gananciaTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gananciaTotal.setText("0");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("Ganancia Total:");

        jefe2Gastos.setBackground(new java.awt.Color(255, 255, 255));
        jefe2Gastos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jefe2Gastos.setText("0");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Gastos:");

        gerente2Gastos.setBackground(new java.awt.Color(255, 255, 255));
        gerente2Gastos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gerente2Gastos.setText("0");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setText("Gastos:");

        gananciasNetas.setBackground(new java.awt.Color(255, 255, 255));
        gananciasNetas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gananciasNetas.setText("0");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Ganancias Netas:");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Administrar Personal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ensambladores2Gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gananciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(302, 302, 302))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel4)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(botones2Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pantallas2Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pines2Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(camaras2Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(ensambladores2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)
                        .addComponent(producidos2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel15)
                        .addGap(10, 10, 10)
                        .addComponent(producidos2Total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botones2Gastos, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(botones2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pantallas2Gastos, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(pantallas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pines2Gastos, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(pines2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(camaras2Gastos, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(camaras2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gananciasNetas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(10, 10, 10)
                                        .addComponent(jefe2Gastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jefe2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(12, 12, 12)
                                        .addComponent(gerente2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(gerente2Gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(10, 10, 10)
                                .addComponent(diasRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botones2Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pantallas2Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pines2Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camaras2Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel12)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(camaras2)
                        .addGap(6, 6, 6)
                        .addComponent(camaras2Gastos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botones2)
                                .addGap(6, 6, 6)
                                .addComponent(botones2Gastos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(pantallas2))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel23))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(pantallas2Gastos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pines2)
                                .addGap(6, 6, 6)
                                .addComponent(pines2Gastos)))))
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(ensambladores2)
                    .addComponent(jLabel14)
                    .addComponent(producidos2)
                    .addComponent(jLabel15)
                    .addComponent(producidos2Total))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(ensambladores2Gastos)
                    .addComponent(jLabel26)
                    .addComponent(ganancia)
                    .addComponent(jLabel27)
                    .addComponent(gananciaTotal))
                .addGap(39, 39, 39)
                .addComponent(jLabel16)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(gerente2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jefe2)
                            .addComponent(jLabel20)
                            .addComponent(diasRestantes))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jefe2Gastos)
                    .addComponent(jLabel19)
                    .addComponent(dias)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(gerente2Gastos))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(gananciasNetas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Planta2Personal personal = new Planta2Personal();
        personal.setLocationRelativeTo(null);
        personal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planta2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static volatile javax.swing.JLabel botones2;
    public static volatile javax.swing.JLabel botones2Gastos;
    public static volatile javax.swing.JProgressBar botones2Progreso;
    public static volatile javax.swing.JLabel camaras2;
    public static volatile javax.swing.JLabel camaras2Gastos;
    public static volatile javax.swing.JProgressBar camaras2Progreso;
    public static volatile javax.swing.JLabel dias;
    public static volatile javax.swing.JLabel diasRestantes;
    public static volatile javax.swing.JLabel ensambladores2;
    public static volatile javax.swing.JLabel ensambladores2Gastos;
    public static volatile javax.swing.JLabel ganancia;
    public static volatile javax.swing.JLabel gananciaTotal;
    public static volatile javax.swing.JLabel gananciasNetas;
    public static volatile javax.swing.JLabel gerente2;
    public static volatile javax.swing.JLabel gerente2Gastos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static volatile javax.swing.JLabel jefe2;
    public static volatile javax.swing.JLabel jefe2Gastos;
    public static volatile javax.swing.JLabel pantallas2;
    public static volatile javax.swing.JLabel pantallas2Gastos;
    public static volatile javax.swing.JProgressBar pantallas2Progreso;
    public static volatile javax.swing.JLabel pines2;
    public static volatile javax.swing.JLabel pines2Gastos;
    public static volatile javax.swing.JProgressBar pines2Progreso;
    public static volatile javax.swing.JLabel producidos2;
    public static volatile javax.swing.JLabel producidos2Total;
    // End of variables declaration//GEN-END:variables
}
