/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.CSVEL;
import Clases.Main;
import static Interfaces.Inicio.planta2;
import static Interfaces.Inicio.planta1;
import javax.swing.JOptionPane;



/**
 *
 * @author ijlem
 */
public class Simulacion extends javax.swing.JFrame {

    /**
     * Creates new form Simulacion
     */
    public Simulacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planta2 = new javax.swing.JButton();
        planta1 = new javax.swing.JButton();
        ambas = new javax.swing.JButton();
        guardarHistorico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        planta2.setBackground(new java.awt.Color(255, 255, 255));
        planta2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        planta2.setText("Observar planta 2 (Xperia 10 III)");
        planta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta2ActionPerformed(evt);
            }
        });
        getContentPane().add(planta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, 303, -1));

        planta1.setBackground(new java.awt.Color(255, 255, 255));
        planta1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        planta1.setText("Observar planta 1 (Xperia 10 IV)");
        planta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta1ActionPerformed(evt);
            }
        });
        getContentPane().add(planta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, -1, -1));

        ambas.setBackground(new java.awt.Color(255, 255, 255));
        ambas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ambas.setText("Observar ambas plantas");
        ambas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambasActionPerformed(evt);
            }
        });
        getContentPane().add(ambas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, 303, -1));

        guardarHistorico.setBackground(new java.awt.Color(255, 255, 255));
        guardarHistorico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        guardarHistorico.setText("Guardar Data Actual");
        guardarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(guardarHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 274, 303, -1));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel1.setText("Sony");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 11, -1, -1));

        dashboard.setBackground(new java.awt.Color(255, 255, 255));
        dashboard.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dashboard.setText("Acceder al Dashboard");
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 325, 303, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 330, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void planta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta2ActionPerformed
        Inicio.planta2.setLocationRelativeTo(null);
        Inicio.planta2.setVisible(true);
    }//GEN-LAST:event_planta2ActionPerformed

    private void planta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta1ActionPerformed
        Inicio.planta1.setLocationRelativeTo(null);
        Inicio.planta1.setVisible(true);
    }//GEN-LAST:event_planta1ActionPerformed

    private void ambasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambasActionPerformed
        Inicio.planta2.setLocationRelativeTo(null);
        Inicio.planta2.setVisible(true);
        Inicio.planta1.setLocationRelativeTo(planta2);
        Inicio.planta1.setVisible(true);
        
    }//GEN-LAST:event_ambasActionPerformed

    private void guardarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarHistoricoActionPerformed
        if((Main.dias - Main.diasTranscurridos) > 5){
                Main.diasTranscurridos = Main.dias;
                Main.telefonos1Ensamblados = Main.producidos1Total;
                Main.gananciasNetas1 = Main.gananciaTotal1 - (Main.botones1Gastos+Main.camaras1Gastos+Main.pantallas1Gastos+Main.pines1Gastos+Main.gerente1Gastos+Main.jefe1Gastos);
                Main.telefonos2Ensamblados = Main.producidos2Total;
                Main.gananciasNetas2 = Main.gananciaTotal2- (Main.botones2Gastos+Main.camaras2Gastos+Main.pantallas2Gastos+Main.pines2Gastos+Main.gerente2Gastos+Main.jefe2Gastos);
                CSVEL csvEscritor = new CSVEL();
                csvEscritor.GuardarHistorico(); 
                JOptionPane.showMessageDialog(null, "Data guardada exitósamente.");
        }else{
            JOptionPane.showMessageDialog(null, "Debes esperar a que transcurran 5 días antes de volver a guardar la data.");
        }
    }//GEN-LAST:event_guardarHistoricoActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        Graficos graficos = new Graficos();
        graficos.setLocationRelativeTo(null);
        graficos.setVisible(true);
    }//GEN-LAST:event_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambas;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton guardarHistorico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton planta1;
    private javax.swing.JButton planta2;
    // End of variables declaration//GEN-END:variables
}
